nodeLinker: node-modules

supportedArchitectures:
  os:
    - linux
    - current
  cpu:
    - x64
    - current

packageExtensions:
  "@nestjs/common@*":
    dependencies:
      reflect-metadata: "*"
